### ISSUE TITLE
$ dollar sign graphic for filter by price for search page

### ISSUE THREAD

**Issue by robyng** [Healthy-Plate-Project/Healthy-Eating-App#101]

**Comment by johndavis92790** [comment]
Similar to the star rating component, but needs to have a high and low, not just high. Like a row of 4 white dollar signs and if you click the 3rd one, it will turn the first 3 dollar signs green, then if you click the 2nd one, it will turn the first one back to white and then the `min_price` would be 2 and the `max_price` would be 3. I will write an algorithm to handle this to determine which dollar signs to turn green and which ones turn white. It probably needs a clear button next to it as well to turn them all back to white. We should probably add a clear button to the star rating component too.

**Comment by robyng** [comment]
SVG version
