### ISSUE TITLE
Create single restaurant result page

### ISSUE THREAD

**Issue by johndavis92790** [Healthy-Plate-Project/Healthy-Eating-App#12]
-Heart icon for favoriting a restaurant
-Dollar icon for listing average price of a restaurant
-Photos, selection of photos feed (show limited amount of photos, default most recent, click see all to view full feed on separate component or page TBD)
-Reviews, selection of reviews (default sort  by recent)
-Map it, hyperlink address on google maps
-Phone number, tel hyperlink

Other:
change styles to name of file it is using the styles in (change RobynStyle.tsx to SingleSearchResultStyles.tsx naming convention)

**Comment by johndavis92790** [comment]
Will post here the json data that we will get from google when that has been tested.

**Comment by johndavis92790** [comment]
@Kimberly-Rodriguez Use the `getRestaurant()` server call to get the dummy data. Its ready to go!

**Comment by johndavis92790** [comment]
Need to display if this is a favorite or not for the specific user. Maybe just some kind of icon that turns yellow if it is and grey if its not? Will make api call to check if single restaurant is a favorite or not, this api call will be called: `checkIfFavorite()`

**Comment by robyng** [comment]
Creating SingleRestaurant page

**Comment by robyng** [comment]
@MatteoThomas @johndavis92790 Dang, the API call broke since last merge into develop. Pull 122 https://github.com/Healthy-Plate-Project/Healthy-Eating-App/pull/122

**Comment by MatteoThomas** [comment]
Ok, I'll check it out

**Comment by MatteoThomas** [comment]
What error are you getting? It seems to work for me?

**Comment by robyng** [comment]
When I press Single Result in menu it was bringing in a restaurant, but no longer is now. There are a couple errors. 
1. Failed to load resource: net::ERR_CONNECTION_REFUSED for the restaurant api
2. AxiosError code"ERR_NETWORK"

**Comment by MatteoThomas** [comment]
I hate to ask, have you pulled recently?

**Comment by robyng** [comment]
Yes I am up to date. Does test api call on home page work for you still?
I'll try on my other computer.

**Comment by robyng** [comment]
@MatteoThomas is working on my other computer now. Weird! Thanks for checking yours.
