### ISSUE TITLE
Create restaurant advanced search page

### ISSUE THREAD

**Issue by johndavis92790** [Healthy-Plate-Project/Healthy-Eating-App#14]
Just build the basic front end inputs for now, we will build the functionality in other tickets.

**Comment by robyng** [comment]
Robyn 
Input: 
1, location browser location / GPS location "My Location" or type city, state, zip, component will convert to lat and long - REQUIRED 
2. Keyword (thai, bbq, gluten free, vegan, etc) - OPTIONAL
3. Radius to location 10 mi, 25 mi, etc convert to meters backend - OPTIONAL
4. min price and max price $ $$ $$$ $$$$ (integers 1-4 on both, max cannot be lower than min) - OPTIONAL
5. Open now? True or False (boolean) - OPTIONAL
-----------------------------------------------------------------------------------------------------------------
Matt
   1. goes on main page search
  1. through 5. on an advanced search page

All in one form
Create one object from form data

**Comment by johndavis92790** [comment]
The open now should just be a radio checkbox, on or off.

**Comment by johndavis92790** [comment]
Functions to convert miles to meters and vise versa:
```
function convertMetersToMiles(meters: number) {
  return meters * 0.000621371192;
}
function  convertMilesToMeters(miles: number) {
  return miles * 1609.344;
}
```

Utility functions like this should live in the `utils` directory, either in the `helpers.tsx` file or in its own file depending on the complexity or scope.

UPDATE - Added!

**Comment by johndavis92790** [comment]
The ability to search by address, zip code, etc will be done with the Google Geocoding API:
https://developers.google.com/maps/documentation/geocoding/start

We should also add the Google Place Autocomplete API to the input field, would be super intuitive:
https://developers.google.com/maps/documentation/places/web-service/autocomplete
