### ISSUE TITLE
[Bug] 404 Error on Clicking Review Button from the Menu

### ISSUE THREAD

**Issue by suvarna18** [Healthy-Plate-Project/Healthy-Eating-App#198]
The user logs in, favorite a restaurant, and submits a review - When clicking the Review Page to view the review - getting a 
 
404 error

Step 1: Log in to the app:https://dragon-fruit-app.herokuapp.com/reviews

Step 2: Perform a search and get search results. 

Step 3: Open a result page. Ex: Veggie Grill. 

Step 4: Mark it favorite.

Step 5: Create a Review by selecting the "stars" and writing into the "text area". Press Submit.

Step 6: Click the Review button from Menu on the Home Page - Get a 404 error

 <img width="1253" alt="Screen Shot 2023-04-05 at 1 43 37 PM" src="https://user-images.githubusercontent.com/5298811/230208797-7bd21596-3229-4de5-901e-3c6992810b06.png">

**Comment by johndavis92790** [comment]
This should be fixed with the latest changes. That button should only be shown if you are logged in currently.
