### ISSUE TITLE
Connect github repo to GCP

### ISSUE THREAD

**Issue by PaulWGeorge** [Healthy-Plate-Project/Healthy-Eating-App#29]

**Comment by PaulWGeorge** [comment]
https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github

**Comment by johndavis92790** [comment]
We need to connect this instance to the `main` branch, then create a second instance that is connected to the `develop` branch. I created a second `yaml` file called `demo.yaml` that will be used for the `develop` branch. You use `npm run deploy` for `app.yaml` and run `npm run demoDeploy` for `demo.yaml`. Both branches need to auto build and deploy when new changes are pushed to the branches.

**Comment by PaulWGeorge** [comment]
I am connecting the repo to GCP. I will need to add the app email account.

So I made a github with that email. I need Kimberly to sign off and give access to account for github access. Then I can proceed.

**Comment by PaulWGeorge** [comment]
This will allow me to download cloud build on the repo:


![Image](https://user-images.githubusercontent.com/88292917/187095536-84e46e3e-ab32-48a0-9e8d-cfe6e57432e9.png)

I will not do it on personal repo for account. I will do it on the app page once I get permission

**Comment by johndavis92790** [comment]
I have admin access to the github too, it's not longer only under Kimberly's control, I will try and get to that tonight. I will also setup you to have admin access as well to the repo.

**Comment by PaulWGeorge** [comment]
These helped:
https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github
https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github

Should be connected. I created triggers for both main and develop. Just need to test.

**Comment by johndavis92790** [comment]
@PaulWGeorge  Can you also create step by step instructions for setting up an instance like these also? Thanks!

**Comment by PaulWGeorge** [comment]
@johndavis92790 Do you mean a guide for creating the triggers and setting up the cloud build repo connection?

**Comment by johndavis92790** [comment]
> @johndavis92790 Do you mean a guide for creating the triggers and setting up the cloud build repo connection?

Yes that would be great. It would just be very helpful for everyone else if they knew the basics to this GCP stuff in this context since online videos and documentation are not that helpful haha. Thanks Paul!
