### ISSUE TITLE
Documentation on creating a basic frontend/backend GCP instance

### ISSUE THREAD

**Issue by johndavis92790** [Healthy-Plate-Project/Healthy-Eating-App#36]
Create new doc in wiki explaining the steps that are necessary to create the basic GCP structure

**Comment by PaulWGeorge** [comment]
wiki created: https://github.com/Healthy-Plate-Project/Healthy-Eating-App/wiki/How-to-set-up-GCP-frontend-backend-instance

**Comment by PaulWGeorge** [comment]
@johndavis92790 If this looks good to you we will close this story.
