### ISSUE TITLE
Debug version 20220817t192023 on GCP for App Engine new deploy

### ISSUE THREAD

**Issue by PaulWGeorge** [Healthy-Plate-Project/Healthy-Eating-App#40]

**Comment by johndavis92790** [comment]
Can you post a link on here to see these instances on GCP?

**Comment by PaulWGeorge** [comment]
https://console.cloud.google.com/appengine/versions?serviceId=default&versionId=20220815t221214&authuser=3&organizationId=0&project=healthy-eating-project-359101

**Comment by PaulWGeorge** [comment]
https://console.cloud.google.com/appengine/versions?serviceId=default&versionId=20220815t221214&authuser=3&organizationId=0&project=healthy-eating-project-359101

**Comment by PaulWGeorge** [comment]
New version "20220828t140542" updated from newest version on Github. Works!
