### ISSUE TITLE
Is our develop appspot being indexed by search engines?

### ISSUE THREAD

**Issue by robyng** [Healthy-Plate-Project/Healthy-Eating-App#41]
Is our develop live link being indexed by google? Do we need to add 301 to the develop live url? I don't want to happen to us what happened to this guy. https://stackoverflow.com/questions/7315003/appspot-com-url-shows-up-in-google-search-results-instead-of-custom-domain-name[#41](https://github.com/Healthy-Plate-Project/Healthy-Eating-App/issues/41)

**Comment by johndavis92790** [comment]
We already have this in our build file, Google does listen to this setting, so no need to do anything right now. We will need to remove this setting for our production version eventually but no need right now.
http://www.robotstxt.org/robotstxt.html

**Comment by robyng** [comment]
Where is it in the build file? Is it a robots.txt? Can you screenshot it or tell me how I can view it? Thanks @johndavis92790

**Comment by johndavis92790** [comment]
There is a robots.txt file that has that setting in the client/public directory. So when we setup our GCP to have development and production server instances, we will turn that off on the production instance and keep it on in the develop instance. But that's down the line, no need to worry about it now.
