### ISSUE TITLE
Write Review

### ISSUE THREAD

**Issue by suvarna18** [Healthy-Plate-Project/Healthy-Eating-App#56]

**Comment by johndavis92790** [comment]
This can initially just be a simple input page to input a name(text), special diet of choice(dropdown menu), rating(1-5 stars) and message. We can integrate it with logged in users later. We can also add photo upload later. We need to also send a userId to make that association.

**Comment by johndavis92790** [comment]
We should save the `place_id` that we get from Google to reference the restaurant to the reviews that are left on our site. This will need to check if this restaurant has already been saved or not, that api call will be called: `saveRestaurant()`. 

Then once the restaurant has been saved in our database or is already found, we will need to save the review, I will name this api call as: `saveReview()`.

**Comment by robyng** [comment]
Okay I'm going to start with star reviews

**Comment by robyng** [comment]
Okay I'm going to start with star reviews

**Comment by robyng** [comment]
following this for accessibility https://stackoverflow.com/questions/17541614/use-images-instead-of-radio-buttons
