### ISSUE TITLE
Rework Global styles

### ISSUE THREAD

**Issue by robyng** [Healthy-Plate-Project/Healthy-Eating-App#87]

**Comment by robyng** [comment]
global styles for App that sets the background color gray needs to be reworked. On longer pages white space shows. The height is currently set to 100vh, I thought it should be 100% but then that messes up styles on home page. Want to work with matt on this.

**Comment by MatteoThomas** [comment]
I'll upload the new home page background image and start working on this today.

**Comment by MatteoThomas** [comment]
I edited the HomeStyles and globalStyles files, and added a new background image in the home page component - pages/Home/index.tsx. This got rid of the white space.
